---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  # stop the build if yamllint fails
  yamllint `git ls-files '*.yaml' '*.yml'`
  # stop the build if there are Python syntax errors or undefined names
  flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
  # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
  flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
platforms:
  - name: centos-7
    image: "ghcr.io/hspaans/molecule-container-centos:7"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ../resources/playbooks/converge.yml
    prepare: ../resources/playbooks/prepare.yml
verifier:
  name: testinfra
  directory: ../resources/tests/
